   export const event=[{
      id: 1,
      title: "Team Meeting",
      date: "2023-06-15",
      time: "10:00 AM - 11:00 AM",
      type: "Work",
      description: "Weekly team sync-up",
    },
    {
      id: 2,
      title: "Project Deadline",
      date: "2023-06-16",
      time: "All Day",
      type: "Work",
      description: "Final submission for Project X",
    },
    {
      id: 3,
      title: "Client Call",
      date: "2023-06-17",
      time: "2:00 PM - 3:00 PM",
      type: "Work",
      description: "Quarterly review with ABC Corp",
    },
    {
      id: 4,
      title: "Gym Session",
      date: "2023-06-18",
      time: "6:00 PM - 7:00 PM",
      type: "Personal",
      description: "Cardio and strength training",
    },
    {
      id: 5,
      title: "Birthday Party",
      date: "2023-06-19",
      time: "7:00 PM - 10:00 PM",
      type: "Personal",
      description: "John's 30th birthday celebration",
    },
  ]